//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DllTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DllTests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;SEM:16&quot;,&quot;shortName&quot;:&quot;16&quot;,&quot;longName&quot;:&quot;MEYLAN Lycée du Grésivaudan / CORENC Montfleury / PONT-DE-CLAIX Gendarmerie&quot;,&quot;color&quot;:&quot;739ECC&quot;,&quot;textColor&quot;:&quot;FFFFFF&quot;,&quot;mode&quot;:&quot;BUS&quot;,&quot;type&quot;:&quot;PROXIMO&quot;},{&quot;id&quot;:&quot;SEM:C4&quot;,&quot;shortName&quot;:&quot;C4&quot;,&quot;longName&quot;:&quot;Grenoble Victor Hugo / Eybens Le Verderet&quot;,&quot;color&quot;:&quot;FFC900&quot;,&quot;textColor&quot;:&quot;000000&quot;,&quot;mode&quot;:&quot;BUS&quot;,&quot;type&quot;:&quot;CHRONO&quot;},{&quot;id&quot;:&quot;SEM:13&quot;,&quot;shortName&quot;:&quot;13&quot;,&quot;longName&quot;:&quot;Meylan Lycée du Grésivaudan / Poisat Prémol&quot;,&quot;color&quot;:&quot;00BC9E&quot;,&quot;textColor&quot;:&quot;FFFFFF&quot;,&quot;mode&quot;:&quot;BUS&quot;,&quot;type&quot;:&quot;PROXIMO&quot;}].
        /// </summary>
        internal static string DetailBonne {
            get {
                return ResourceManager.GetString("DetailBonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;SEM:C1&quot;,&quot;shortName&quot;:&quot;C1&quot;,&quot;longName&quot;:&quot;GRENOBLE Cité Jean Macé / MEYLAN Maupertuis&quot;,&quot;color&quot;:&quot;FFE000&quot;,&quot;textColor&quot;:&quot;000000&quot;,&quot;mode&quot;:&quot;BUS&quot;,&quot;type&quot;:&quot;CHRONO&quot;}].
        /// </summary>
        internal static string DetailChavant {
            get {
                return ResourceManager.GetString("DetailChavant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;SEM:57&quot;,&quot;shortName&quot;:&quot;57&quot;,&quot;longName&quot;:&quot;GRENOBLE Victor Hugo / ST ISMIER Bois Français&quot;,&quot;color&quot;:&quot;522E91&quot;,&quot;textColor&quot;:&quot;FFFFFF&quot;,&quot;mode&quot;:&quot;BUS&quot;,&quot;type&quot;:&quot;FLEXO&quot;},{&quot;id&quot;:&quot;SEM:C4&quot;,&quot;shortName&quot;:&quot;C4&quot;,&quot;longName&quot;:&quot;Grenoble Victor Hugo / Eybens Le Verderet&quot;,&quot;color&quot;:&quot;FFC900&quot;,&quot;textColor&quot;:&quot;000000&quot;,&quot;mode&quot;:&quot;BUS&quot;,&quot;type&quot;:&quot;CHRONO&quot;},{&quot;id&quot;:&quot;SEM:C1&quot;,&quot;shortName&quot;:&quot;C1&quot;,&quot;longName&quot;:&quot;GRENOBLE Cité Jean Macé / MEYLAN Maupertuis&quot;,&quot;color&quot;:&quot;FFE000&quot;,&quot;textColor&quot;:&quot;000000&quot;,&quot;mode&quot;:&quot;BUS&quot;,&quot;type&quot;:&quot;CHRONO&quot;}].
        /// </summary>
        internal static string DetailMartin {
            get {
                return ResourceManager.GetString("DetailMartin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{
        ///&quot;id&quot;: &quot;SEM:1986&quot;,
        ///&quot;name&quot;: &quot;GRENOBLE, CASERNE DE BONNE&quot;,
        ///&quot;lon&quot;: 5.72533,
        ///&quot;lat&quot;: 45.18506,
        ///&quot;lines&quot;: [
        ///&quot;SEM:13&quot;,
        ///&quot;SEM:16&quot;,
        ///&quot;SEM:C4&quot;,
        ///&quot;SEM:13&quot;,
        ///&quot;SEM:16&quot;,
        ///&quot;SEM:C4&quot;
        ///]
        ///},
        ///{
        ///&quot;id&quot;: &quot;SEM:1987&quot;,
        ///&quot;name&quot;: &quot;GRENOBLE, CASERNE DE BONNE&quot;,
        ///&quot;lon&quot;: 5.72542,
        ///&quot;lat&quot;: 45.18509,
        ///&quot;lines&quot;: [
        ///&quot;SEM:16&quot;,
        ///&quot;SEM:16&quot;
        ///]
        ///},
        ///{
        ///&quot;id&quot;: &quot;SEM:1990&quot;,
        ///&quot;name&quot;: &quot;GRENOBLE, CHAVANT&quot;,
        ///&quot;lon&quot;: 5.7312,
        ///&quot;lat&quot;: 45.18551,
        ///&quot;lines&quot;: [
        ///&quot;SEM:C1&quot;,
        ///&quot;SEM:C1&quot;
        ///]
        ///},
        ///{
        ///&quot;id&quot;: &quot;SEM:0753&quot;,
        ///&quot;name&quot;: &quot;GRENOBLE, DOCTEUR MARTIN&quot;,
        ///&quot;lon&quot;: 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSon {
            get {
                return ResourceManager.GetString("JSon", resourceCulture);
            }
        }
    }
}
